-- Flyway migration: Initial schema for AUDIT_LOG and CUSTOMER_PROFILE (MySQL)

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
  AUDIT_UUID VARCHAR(100) PRIMARY KEY,
  CRUD_VALUE CHAR(1) NOT NULL,
  USER_ID VARCHAR(100) NOT NULL,
  WS_ID VARCHAR(100),
  PRGM_ID VARCHAR(100),
  HOST_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LOCAL_TS TIMESTAMP NULL,
  ACPT_TS TIMESTAMP NULL,
  ACPT_TS_UTC_OFST VARCHAR(10),
  CHANGED_FIELDS JSON,
  REMARKS TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS CUSTOMER_PROFILE (
  CST_ID BIGINT PRIMARY KEY,
  CUSTID_TYPE VARCHAR(100),
  CUSTID_ITEM VARCHAR(100) NOT NULL UNIQUE,

  CSTDET_TYPE VARCHAR(100),
  CSTDET_DOB DATE,
  CSTDET_STATUS VARCHAR(100),

  CSTDET_MOBILE VARCHAR(100),
  CSTDET_EMAIL VARCHAR(100),

  CSTNAME_FIRST VARCHAR(100),
  CSTNAME_MIDDLE VARCHAR(100),
  CSTNAME_LAST VARCHAR(100),

  CSTADD_PERMANENT VARCHAR(200),
  CSTADD_CURRENT VARCHAR(200),

  CSTPOI_TYPE VARCHAR(100),
  CSTPOI_VALUE VARCHAR(100) UNIQUE,
  CSTPOI_START DATE,
  CSTPOI_END DATE,

  CONTACT_TYPE VARCHAR(50),
  CONTACT_VALUE VARCHAR(100),

  CST_EFCTV_DATE DATE NOT NULL,

  AUDIT_UUID VARCHAR(100),
  AUDIT_DETAILS JSON,

  CONSTRAINT FK_CUSTOMER_AUDIT
    FOREIGN KEY (AUDIT_UUID) REFERENCES AUDIT_LOG(AUDIT_UUID)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;



